<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <OutputType>Exe</OutputType>
    <TargetFramework>net8.0</TargetFramework>
    <GeneratePackageOnBuild>false</GeneratePackageOnBuild> 
  </PropertyGroup>

  <ItemGroup>
    <PackageReference Include="Blauhaus.Analytics.Console" Version="2.1.1" />
    <PackageReference Include="Microsoft.Azure.NotificationHubs" Version="4.2.0" />
    <PackageReference Include="Microsoft.Extensions.DependencyInjection" Version="8.0.0" />
  </ItemGroup>

  <ItemGroup>
    <ProjectReference Include="..\Blauhaus.Push.Server\Blauhaus.Push.Server.csproj" />
  </ItemGroup>

</Project>
