trigger:
- release/*

pool:
  vmImage: 'windows-2022'

variables:
  solution: 'src\Blauhaus.Push.sln'
  buildPlatform: 'Any CPU'
  VersionName: $[replace(variables['Build.SourceBranchName'], 'refs/heads/release/', '')]
  buildConfiguration: 'Release'
  appxPackageDir: '$(build.artifactStagingDirectory)\AppxPackages\\'

steps:
- powershell: Write-Host "Branch Name $(Build.SourceBranchName)"

- task: CmdLine@2
  displayName: Install MAUI
  inputs:
    script: 'dotnet workload install maui'

- task: Bash@3
  displayName: Restore nuget
  inputs:
    targetType: 'inline'
    script: |
        dotnet restore '$(solution)' 

#- task: MSBuild@1
#  inputs:
#    solution: './src/Blauhaus.Push.Client/Blauhaus.Push.Client.csproj'
#    platform: 'Any CPU'
#    configuration: 'Release'
#    clean: true
#    msbuildArgs: '/p:TargetFramework=Xamarin.iOS10 /t:restore;build;pack /p:PackageVersion=$(Branch Name) /p:PackageOutputPath=$(appxPackageDir)'
    
#- task: MSBuild@1
#  inputs:
#    solution: './src/Blauhaus.Push.Client/Blauhaus.Push.Client.csproj'
#    platform: 'Any CPU'
#    configuration: 'Release'
#    clean: true
#    msbuildArgs: '/p:TargetFramework=MonoAndroid10.0 /t:restore;build;pack /p:PackageVersion=$(Branch Name) /p:PackageOutputPath=$(appxPackageDir)'
    
#- task: MSBuild@1
#  inputs:
#    solution: './src/Blauhaus.Push.Client/Blauhaus.Push.Client.csproj'
#    platform: 'Any CPU'
#    configuration: 'Release'
#    clean: true
#    msbuildArgs: '/p:TargetFramework=uap10.0.19041 /t:restore;build;pack /p:PackageVersion=$(Branch Name) /p:PackageOutputPath=$(appxPackageDir)'

- task: Bash@3
  displayName: Build
  inputs:
    targetType: 'inline'
    script: | 
        dotnet publish ./src/Blauhaus.Push.Abstractions/Blauhaus.Push.Abstractions.csproj -f netstandard2.0 -c Release -o $(build.sourcesdirectory) -p:Version=$(Branch Name)
        dotnet publish ./src/Blauhaus.Push.Abstractions/Blauhaus.Push.Abstractions.csproj -f net7.0 -c Release -o $(build.sourcesdirectory) -p:Version=$(Branch Name)
        dotnet publish ./src/Blauhaus.Push.Client/Blauhaus.Push.Client.csproj -f netstandard2.0 -c Release -o $(build.sourcesdirectory) -p:Version=$(Branch Name)
        dotnet publish ./src/Blauhaus.Push.Client/Blauhaus.Push.Client.csproj -f net7.0 -c Release -o $(build.sourcesdirectory) -p:Version=$(Branch Name)
        dotnet publish ./src/Blauhaus.Push.Client.Maui/Blauhaus.Push.Client.Maui.csproj -f net7.0 -c Release -o $(build.sourcesdirectory) -p:Version=$(Branch Name)
        dotnet publish ./src/Blauhaus.Push.Client.Maui/Blauhaus.Push.Client.Maui.csproj -f net7.0-ios -c Release -o $(build.sourcesdirectory) -p:Version=$(Branch Name)
        dotnet publish ./src/Blauhaus.Push.Client.Maui/Blauhaus.Push.Client.Maui.csproj -f net7.0-android -c Release -o $(build.sourcesdirectory) -p:Version=$(Branch Name)
        dotnet publish ./src/Blauhaus.Push.Client.Maui/Blauhaus.Push.Client.Maui.csproj -f net7.0-windows10.0.19041 -c Release -p:PublishReadyToRun=false -o $(build.sourcesdirectory) -p:Version=$(Branch Name)
        dotnet publish ./src/Blauhaus.Push.Server/Blauhaus.Push.Server.csproj -f net7.0 -c Release -o $(build.sourcesdirectory) -p:Version=$(Branch Name)
        dotnet publish ./src/Blauhaus.Push.TestHelpers/Blauhaus.Push.TestHelpers.csproj -f net7.0 -c Release -o $(build.sourcesdirectory) -p:Version=$(Branch Name)
 
- task: CopyFiles@2
  inputs:
    SourceFolder: '$(build.sourcesdirectory)'
    Contents: '**\bin\$(BuildConfiguration)\**\*.nupkg'
    TargetFolder: '$(build.artifactstagingdirectory)'

- task: NuGetCommand@2
  inputs:
    command: 'push'
    packagesToPush: '$(Build.ArtifactStagingDirectory)/**/*.nupkg;!$(Build.ArtifactStagingDirectory)/**/*.symbols.nupkg'
    nuGetFeedType: 'external'
    publishFeedCredentials: 'Blauhaus Nuget'

